{% set name = "pyranges" %}
{% set version = "0.1.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 86a3ea4c46ff7dda9b70dd67da09b374bec79863b4ea904018606003004f97f4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  run_exports:
    - {{ pin_subpackage('pyranges', max_pin="x.x") }}

requirements:
  host:
    - python >=3.11,<3.13
    - setuptools-scm
    - pip
  run:
    - python >=3.11,<3.13
    - pandas
    - ncls >=0.0.63
    - tabulate
    - sorted_nearest >=0.0.33
    - natsort

test:
  imports:
    - pyranges

about:
  home: "https://github.com/endrebak/pyranges"
  license: MIT
  license_family: MIT
  summary: "Performant Pythonic GenomicRanges"
  license_file: LICENSE
  dev_url: "https://github.com/endrebak/pyranges"
  doc_url: "https://pyranges.readthedocs.io"

extra:
  identifiers:
    - biotools:PyRanges
    - doi:10.1093/bioinformatics/btz615
