{% set version = "0.1.2" %}

package:
  name: graphembed
  version: {{ version }}

build:
  number: 0
  run_exports:
      - {{ pin_subpackage('graphembed', max_pin="x.x") }}
  skip: True  # [osx]
source:
  url: https://github.com/jianshu93/graphembed/archive/v{{ version }}.tar.gz
  sha256: e8fb5f46d004f8f6c110a712ca359d0789e456c39fa0f58cdd953c881fd970a3

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ compiler('c') }}
    - rust >=1.39
    - make
    - cmake

test:
  commands:
    - graphembed -h

about:
  home: https://github.com/jean-pierreBoth/graphembed
  license: MIT
  summary: Efficient Graph Embedding via Recursive Sketching or High-order Transitivity Preserving with Benchmarking
extra:
  maintainers:
   - Jean Pierre-Both
   - Jianshu Zhao
